desc: > 
  Отсутствие кредитной истории может означать многое, включая молодой возраст или предпочтение наличных 
  денег. Без традиционных данных человеку, у которого практически нет кредитной истории, скорее всего, будет отказано. 
  Поставщики потребительского кредитования должны точно определить, какие клиенты могут погасить кредит, а какие нет, 
  и данные имеют решающее значение. Если бы наука о данных могла помочь лучше прогнозировать возможности погашения 
  долга, кредиты могли бы стать более доступными для тех, кто может получить от них наибольшую выгоду. **Данная работа 
  по оценке рисков дефолта потенциальных клиентов позволит поставщикам потребительского кредитования принимать больше 
  заявок на кредит. Это может улучшить жизнь людей, которым исторически отказывали в кредите из-за отсутствия кредитной 
  истории.**
add_desc: >
  В настоящее время поставщики потребительского кредитования используют различные статистические методы 
  и методы машинного обучения для прогнозирования кредитного риска. Эти модели обычно называют картами показателей. В 
  реальном мире поведение клиентов постоянно меняется, поэтому каждую систему показателей необходимо регулярно 
  обновлять, а это требует времени. Стабильность системы показателей в будущем имеет решающее значение, 
  поскольку внезапное падение производительности означает, что кредиты в среднем будут выдаваться худшим клиентам. Суть 
  проблемы заключается в том, что поставщики кредитов не могут обнаружить потенциальные проблемы раньше, чем станут 
  заметны первые сроки погашения этих кредитов. Учитывая время, необходимое для повторной разработки, проверки и 
  внедрения системы показателей, стабильность крайне желательна. Существует компромисс между стабильностью модели и ее 
  производительностью, и перед развертыванием необходимо достичь баланса.
fields_desc: |
  -  case_id - Уникальный идентификатор.
  -  WEEK_NUM - номер недели, используется для группировки и расчета метрики gini stability.
  -  :blue[age_years] - Возраст клиента.
  -  :blue[employedfrom] - Общий трудовой стаж (в днях).
  -  :blue[incometype_1044T] - Вид дохода.
  -  :blue[pmtnum_254L] - Общее количество платежей по кредиту осуществленных клиентом. 
  -  :blue[num_cred_closed] - Количество закрытых кредитов.
  -  :blue[annuity_780A] - Размер ежемесячного платежа.
  -  :blue[debt_outstand_total] - Общая сумма непогашенного долга.
  -  :blue[isbidproduct] - Флаг указывающий является ли продукт перекрестной продажей.
  -  :blue[numberofoverdueinstlmaxdat_148D] - Сколько дней прошло с последней просрочки платежа по закрытому договору.
  -  :blue[total_amount_closed_contracts] - Общая сумма закрытых контрактов.
  -  :blue[credamount_770A] - Cумма активного кредита.
  -  :blue[num_cred_active] - Количество активных кредитов.
  -  :blue[mobilephncnt_593L] - Количество клиентов с таким же номером мобильного телефона.
  -  :blue[tax_amount_max] - Максимальный размер налога.
  -  :blue[maininc_215A] - Размер основного дохода.
  -  :red[target] - Целевой признак. 1: Был дефолт по кредиту, 0: Дефолта не было
mail: mailto:frolovaleh@gmail.com
tg: https://t.me/FrolovO1eg
hyp_titles: ["Возраст - категории дохода", "Ежемесячный платеж - размер налога", 'Стаж  target',
             'Размер кредита - непогашенный долг', 'Дата последней просрочки - target',
             'Общая сумма - количество закрытых кредитов']
hypotheses: [':red[Гипотеза 1.] Размер основного дохода клиента :blue[(maininc_215A)] сильно зависит от вида дохода
 человека :blue[(Incometype_1044T)]. У работающих клиентов доход выше. У заемщиков с высоким риском дефолта доход
  внутри группы ниже.',
  ':red[Гипотеза 2.] Размер ежемесячного платежа зависит от размера налога. Чем выше налог, тем выше себе может
   позволить клиент размер кредита (следовательно и ежемесячного платежа). Причем чем выше размер ежемесячного платежа,
    тем выше вероятность дефолта.',
  ':red[Гипотеза 3.] Вероятность дефолта зависит от трудового стажа. Чем меньше стаж тем вероятность выше.',
  ':red[Гипотеза 4.] Размер активного кредита зависит от размера непогашенного долга по всем кредитам. Чем выше долг,
   тем ниже размер активного кредита.',
  ':red[Гипотеза 5.] При недавней просрочке по предыдущему кредиту вероятность дефолта по текущему кредиту будет выше.',
  ':red[Гипотеза 6.] Чем больше клиент закрытыл кредитов и чем больше их общая сумма, тем меньше вероятность дефолта.']
hypotheses_conclusion: [':blue[Гипотеза верна.] Сумма основного дохода клиента (maininc_215A) сильно зависит от вида
 дохода человека (Incometype_1044T). У работающих клиентов доход выше, чем у пенсионеров, инвалидов и других. Но
  интерквартильный размах у всех категорий находится в районе 25 - 50 тыс, кроме самозанятых. У заемщиков с высоким
   риском дефолта в большинстве случаев доход внутри группы чуть ниже, по медианному значению.',
  ':red[Гипотеза не верна.] Размер ежемесячного платежа размер налога независимы (коэффициент корреляции 0.1).
   Причем зависимости с целевым признаком (target) тоже нет.',
  ':blue[Гипотеза верна.] Наблюдаем статистически значимую разницу. Клиенты с меньшим стажем чаще имеют дефолт по
   кредиту.',
  'Видим, что размер активного кредита не связан от размером непогашенного долга по всем кредитам. Коэффициент
   корреляции близок к нулю. Также отсутсвует связь с количеством клиентов с таким же номер телефона и количеством
    платеже по кредиту.',
  ':blue[Гипотеза верна.] При недавней просрочке по предыдущему кредиту вероятность дефолта по текущему кредиту будет
   выше. Наблюдаем статистически значимые отличия между двумя группами.',
  ':blue[Гипотеза полностью подтверждена. ] Чем больше клиент закрытыл кредитов и чем больше их общая сумма, тем
   меньше вероятность дефолта. Наблюдается статистически значимая разница между группами с target 0 и 1.'
]
shap_tabs_titles: ["Beeswarm plot", "Scatter plots", 'Force plot']
shap_scatters_conclusion: |
  - Чем больше возраст, тем ниже в среднем вероятность дефолта. Для этой модели характерно, что клиенты моложе 50 имеют
  вероятность дефолта выше, чем клиенты старше 50. Причем те, кто моложе 27 в зоне риска. Также  видна зависимость от
  образования.
  - pmtnum_254L - Общее количество платежей по кредиту, осуществленных клиентом. Начиная с ~ 19 выплат клиенты более
  подвержены дефолту.
  - tax_amount_max: Максимальный размер налога. Чем заемщик платит больше налогов, тем ниже вероятность дефолта.
  - employedfrom - Общий трудовой стаж (в днях относительно даты записи). Чем больше стаж, тем ниже вероятность дефолта.